name: te_autism
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core data science packages
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Jupyter environment
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.4.0
  - ipywidgets>=7.6.0
  
  # Progress bars and utilities
  - tqdm>=4.62.0
  
  # Statistical analysis
  - statsmodels>=0.12.0
  
  # Plotting (optional)
  - plotly>=5.0.0
  
  # Development tools
  - pip
  - ipython>=7.25.0
  
  # Install packages not available in conda via pip
  - pip:
    - openai>=1.0.0
    - krippendorff>=0.5.0
    - python-dotenv>=0.19.0